services:
  postgres:
    container_name: postgres
    image: postgres:14.8-alpine3.18
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

  app:
    container_name: fastapi
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./upload_files:/app/src/uploads
    depends_on:
      - postgres
      - redis
    restart: on-failure
