import pytest
from httpx import AsyncClient
from .data import clean_dates, upload_data


@pytest.mark.parametrize(
    "path, filename",
    [
        ("products/limited", "limited_products.json"),
        ("banners", "banners.json"),
        ("products/popular", "popular_products.json"),
    ],
)
async def test_types_of_products(ac: AsyncClient, path: str, filename: str):
    response = await ac.get(f"api/{path}")
    data = response.json()
    clean_dates(data)
    assert data == upload_data(filename)



async def test_sales(ac: AsyncClient):
    response = await ac.get("api/sales")
    data = response.json()
    clean_dates(data["items"], attrs=("dateFrom",))
    assert data == {
        "currentPage": 1,
        "items": [
            {
                "id": 7,
                "price": "700.0000",
                "title": "Product7",
                "images": [],
                "salePrice": "50.0000",
                "dateTo": "06-09",
            },
            {
                "id": 8,
                "price": "800.0000",
                "title": "Product8",
                "images": [],
                "salePrice": "700.0000",
                "dateTo": "07-09",
            },
        ],
        "lastPage": 1,
    }


@pytest.mark.parametrize(
    "params, result",
    [
        (
            {"filter[name]": "prod"},
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 8,
                        "price": "700.0000",
                        "title": "Product8",
                        "images": [],
                        "category": 3,
                        "count": 8,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                ],
                "lastPage": 2,
            },
        ),
        (
            {"filter[minPrice]": 40, "filter[maxPrice]": 650},
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "filter[available]": False,
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 3,
                        "price": "300.0000",
                        "title": "Product3",
                        "images": [],
                        "category": 3,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [],
                        "reviews": 1,
                        "rating": 1,
                    },
                ],
                "lastPage": 2,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "filter[available]": False,
                "currentPage": 2,
            },
            {
                "currentPage": 2,
                "items": [
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 1,
                        "price": "100.0000",
                        "title": "Product1",
                        "images": [],
                        "category": 1,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 2,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "category": 1,
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "tags[]": [1],
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "tags[]": [1, 2],
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "filter[freeDelivery]": True,
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    }
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "price",
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "rating",
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "rating",
                "sortType": "inc",
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "reviews",
                "filter[available]": False,
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 3,
                        "price": "300.0000",
                        "title": "Product3",
                        "images": [],
                        "category": 3,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [],
                        "reviews": 1,
                        "rating": 1,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                ],
                "lastPage": 2,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "reviews",
                "filter[available]": False,
                "currentPage": 2,
            },
            {
                "currentPage": 2,
                "items": [
                    {
                        "id": 1,
                        "price": "100.0000",
                        "title": "Product1",
                        "images": [],
                        "category": 1,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 2,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "price",
                "filter[available]": False,
                "currentPage": 1,
                "sortType": "inc",
                "limit": 20,
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 1,
                        "price": "100.0000",
                        "title": "Product1",
                        "images": [],
                        "category": 1,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 3,
                        "price": "300.0000",
                        "title": "Product3",
                        "images": [],
                        "category": 3,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [],
                        "reviews": 1,
                        "rating": 1,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "price",
                "filter[available]": False,
                "currentPage": 2,
                "sortType": "inc",
                "limit": 2,
            },
            {
                "currentPage": 2,
                "items": [
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 3,
                        "price": "300.0000",
                        "title": "Product3",
                        "images": [],
                        "category": 3,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [],
                        "reviews": 1,
                        "rating": 1,
                    },
                ],
                "lastPage": 4,
            },
        ),
    ],
)
async def test_catalog(ac: AsyncClient, params, result):

    response = await ac.get(
        "api/catalog",
        params=params,
    )

    data = response.json()
    clean_dates(data["items"])
    assert data == result


@pytest.mark.parametrize(
    "params",
    [
        {"filter[name]": "thing"},
        {
            "filter[minPrice]": 801,
        },
        {"filter[maxPrice]": 10},
        {"category": 100},
        {"tags[]": [100]},
        {"currentPage": 3},
    ],
)
async def test_empty_catalog(ac: AsyncClient, params):
    response = await ac.get(
        "api/catalog",
        params=params,
    )
    current_page = params.get("currentPage", 1)
    last_page = params.get("currentPage")
    if last_page is None:
        last_page = 1
    else:
        last_page = 2
    assert response.json() == {
        "currentPage": current_page,
        "items": [],
        "lastPage": last_page,
    }


async def test_product(ac: AsyncClient):
    response = await ac.get("api/product/8")
    data = response.json()
    data.pop("date")
    clean_dates(data["reviews"])
    assert data == {
        "id": 8,
        "price": "700.0000",
        "title": "Product8",
        "images": [],
        "category": 3,
        "count": 8,
        "description": "Нет описания",
        "freeDelivery": False,
        "tags": [],
        "reviews": [
            {
                "text": "Some text",
                "rate": 5,
                "author": "user1",
                "email": "Не указано",
            }
        ],
        "rating": 5,
        "fullDescription": "Нет полного описания",
        "specifications": [
            {"name": "Spec1", "value": "Value1"},
            {"name": "Spec2", "value": "Value2"},
        ],
    }
