import pytest
from httpx import AsyncClient


def clear_date(products: dict, attrs=("date",)):
    for product in products:
        for attr in attrs:
            product.pop(attr)


async def test_limited_products(ac: AsyncClient):
    response = await ac.get("api/products/limited")
    data = response.json()
    clear_date(data)
    assert data == [
        {
            "id": 1,
            "price": "100.0000",
            "title": "Product1",
            "images": [],
            "category": 1,
            "count": 0,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [{"id": 1, "name": "Tag1"}, {"id": 2, "name": "Tag2"}],
            "reviews": 0,
            "rating": 0,
        },
        {
            "id": 3,
            "price": "300.0000",
            "title": "Product3",
            "images": [],
            "category": 3,
            "count": 0,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [],
            "reviews": 1,
            "rating": 1,
        },
    ]


async def test_banners(ac: AsyncClient):
    response = await ac.get("api/banners")
    data = response.json()
    clear_date(data)
    assert data == [
        {
            "id": 3,
            "price": "300.0000",
            "title": "Product3",
            "images": [],
            "category": 3,
            "count": 0,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [],
            "reviews": 1,
            "rating": 1,
        },
        {
            "id": 5,
            "price": "500.0000",
            "title": "Product5",
            "images": [],
            "category": 2,
            "count": 5,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [{"id": 1, "name": "Tag1"}],
            "reviews": 1,
            "rating": 2,
        },
        {
            "id": 6,
            "price": "600.0000",
            "title": "Product6",
            "images": [],
            "category": 1,
            "count": 6,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [{"id": 1, "name": "Tag1"}, {"id": 2, "name": "Tag2"}],
            "reviews": 1,
            "rating": 5,
        },
        {
            "id": 7,
            "price": "50.0000",
            "title": "Product7",
            "images": [],
            "category": 1,
            "count": 7,
            "description": "Нет описания",
            "freeDelivery": True,
            "tags": [{"id": 1, "name": "Tag1"}, {"id": 2, "name": "Tag2"}],
            "reviews": 1,
            "rating": 4,
        },
        {
            "id": 8,
            "price": "700.0000",
            "title": "Product8",
            "images": [],
            "category": 3,
            "count": 8,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [],
            "reviews": 1,
            "rating": 5,
        },
    ]


async def test_popular_products(ac: AsyncClient):
    response = await ac.get("api/products/popular")
    data = response.json()
    clear_date(data)
    assert data == [
        {
            "id": 3,
            "price": "300.0000",
            "title": "Product3",
            "images": [],
            "category": 3,
            "count": 0,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [],
            "reviews": 1,
            "rating": 1,
        },
        {
            "id": 4,
            "price": "400.0000",
            "title": "Product4",
            "images": [],
            "category": 2,
            "count": 4,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [{"id": 1, "name": "Tag1"}],
            "reviews": 2,
            "rating": 1,
        },
        {
            "id": 5,
            "price": "500.0000",
            "title": "Product5",
            "images": [],
            "category": 2,
            "count": 5,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [{"id": 1, "name": "Tag1"}],
            "reviews": 1,
            "rating": 2,
        },
        {
            "id": 6,
            "price": "600.0000",
            "title": "Product6",
            "images": [],
            "category": 1,
            "count": 6,
            "description": "Нет описания",
            "freeDelivery": False,
            "tags": [{"id": 1, "name": "Tag1"}, {"id": 2, "name": "Tag2"}],
            "reviews": 1,
            "rating": 5,
        },
        {
            "id": 7,
            "price": "50.0000",
            "title": "Product7",
            "images": [],
            "category": 1,
            "count": 7,
            "description": "Нет описания",
            "freeDelivery": True,
            "tags": [{"id": 1, "name": "Tag1"}, {"id": 2, "name": "Tag2"}],
            "reviews": 1,
            "rating": 4,
        },
    ]


async def test_sales(ac: AsyncClient):
    response = await ac.get("api/sales")
    data = response.json()
    clear_date(data["items"], attrs=("dateFrom",))
    assert data == {
        "currentPage": 1,
        "items": [
            {
                "id": 7,
                "price": "700.0000",
                "title": "Product7",
                "images": [],
                "salePrice": "50.0000",
                "dateTo": "06-09",
            },
            {
                "id": 8,
                "price": "800.0000",
                "title": "Product8",
                "images": [],
                "salePrice": "700.0000",
                "dateTo": "07-09",
            },
        ],
        "lastPage": 1,
    }


@pytest.mark.parametrize(
    "params, result",
    [
        (
            {"filter[name]": "Product2"},
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    }
                ],
                "lastPage": 1,
            },
        ),
        (
            {"filter[minPrice]": 40, "filter[maxPrice]": 650},
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "filter[available]": False,
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 3,
                        "price": "300.0000",
                        "title": "Product3",
                        "images": [],
                        "category": 3,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [],
                        "reviews": 1,
                        "rating": 1,
                    },
                ],
                "lastPage": 2,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "filter[available]": False,
                "currentPage": 2,
            },
            {
                "currentPage": 2,
                "items": [
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 1,
                        "price": "100.0000",
                        "title": "Product1",
                        "images": [],
                        "category": 1,
                        "count": 0,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 2,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "category": 1,
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "tags[]": [1],
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "tags[]": [1, 2],
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "filter[freeDelivery]": True,
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    }
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "price",
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "rating",
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                ],
                "lastPage": 1,
            },
        ),
        (
            {
                "filter[minPrice]": 40,
                "filter[maxPrice]": 650,
                "sort": "rating",
                "sortType": "inc",
            },
            {
                "currentPage": 1,
                "items": [
                    {
                        "id": 2,
                        "price": "200.0000",
                        "title": "Product2",
                        "images": [],
                        "category": 2,
                        "count": 10,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 0,
                        "rating": 0,
                    },
                    {
                        "id": 4,
                        "price": "400.0000",
                        "title": "Product4",
                        "images": [],
                        "category": 2,
                        "count": 4,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 2,
                        "rating": 1,
                    },
                    {
                        "id": 5,
                        "price": "500.0000",
                        "title": "Product5",
                        "images": [],
                        "category": 2,
                        "count": 5,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [{"id": 1, "name": "Tag1"}],
                        "reviews": 1,
                        "rating": 2,
                    },
                    {
                        "id": 7,
                        "price": "50.0000",
                        "title": "Product7",
                        "images": [],
                        "category": 1,
                        "count": 7,
                        "description": "Нет описания",
                        "freeDelivery": True,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 4,
                    },
                    {
                        "id": 6,
                        "price": "600.0000",
                        "title": "Product6",
                        "images": [],
                        "category": 1,
                        "count": 6,
                        "description": "Нет описания",
                        "freeDelivery": False,
                        "tags": [
                            {"id": 1, "name": "Tag1"},
                            {"id": 2, "name": "Tag2"},
                        ],
                        "reviews": 1,
                        "rating": 5,
                    },
                ],
                "lastPage": 1,
            },
        ),
    ],
)
async def test_catalog(ac: AsyncClient, params, result):

    response = await ac.get(
        "api/catalog",
        params=params,
    )
    data = response.json()
    clear_date(data["items"])
    assert data == result
