"""empty message

Revision ID: 4800a7edaf44
Revises: e5eb30bfd7f7
Create Date: 2025-02-06 18:47:40.774872

"""

from typing import Sequence, Union

import fastapi_storages.integrations.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4800a7edaf44"
down_revision: Union[str, None] = "e5eb30bfd7f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "address", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "address", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
