"""empty message

Revision ID: 56257023ec65
Revises: 20c18c63f64e
Create Date: 2025-02-04 18:22:10.119734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages.integrations.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "56257023ec65"
down_revision: Union[str, None] = "20c18c63f64e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("text", sa.TEXT(), nullable=False))
    op.add_column(
        "reviews",
        sa.Column(
            "date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "date")
    op.drop_column("reviews", "text")
    # ### end Alembic commands ###
