"""empty message

Revision ID: 8dbd2d53e779
Revises: 834a64069dc4
Create Date: 2025-02-06 18:08:38.924810

"""

from typing import Sequence, Union

import fastapi_storages.integrations.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dbd2d53e779"
down_revision: Union[str, None] = "834a64069dc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "delivery_type",
        existing_type=postgresql.ENUM(
            "ordinary", "express", name="deliverytypeenum"
        ),
        nullable=True,
    )
    op.alter_column(
        "orders",
        "payment_type",
        existing_type=postgresql.ENUM(
            "online", "someone", name="paymenttypeenum"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "payment_type",
        existing_type=postgresql.ENUM(
            "online", "someone", name="paymenttypeenum"
        ),
        nullable=False,
    )
    op.alter_column(
        "orders",
        "delivery_type",
        existing_type=postgresql.ENUM(
            "ordinary", "express", name="deliverytypeenum"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
