"""empty message

Revision ID: 834a64069dc4
Revises: 6b606a65bcf3
Create Date: 2025-02-06 15:53:33.107197

"""

from typing import Sequence, Union

import fastapi_storages.integrations.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "834a64069dc4"
down_revision: Union[str, None] = "6b606a65bcf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "delivery_type",
            sa.Enum("ordinary", "express", name="deliverytypeenum"),
            nullable=False,
        ),
        sa.Column(
            "payment_type",
            sa.Enum("online", "someone", name="paymenttypeenum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("unpaid", "paid", name="orderstatusenum"),
            server_default="unpaid",
            nullable=False,
        ),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders_products_association",
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "order_id", name="idx_uniq_order_product"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders_products_association")
    op.drop_table("orders")
    # ### end Alembic commands ###
