"""empty message

Revision ID: 659c2f0e7a42
Revises: 4800a7edaf44
Create Date: 2025-02-06 18:52:16.165733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages.integrations.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "659c2f0e7a42"
down_revision: Union[str, None] = "4800a7edaf44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "total_cost", sa.Numeric(precision=10, scale=4), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "total_cost")
    # ### end Alembic commands ###
